# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: geoapify
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep purple
    accent: blue
  font: false
  features:
    - navigation.instant
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mkdocs-click
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2022 Paul Kinsvater –
  <a href="#__consent">Change cookie settings</a>
plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
repo_url: https://github.com/kinsvater/geoapify
repo_name: kinsvater/geoapify
nav:
  - Home: index.md
  - Install: install.md
  - Tutorials:
    - example-toy.md
    - tutorial-enrich-locations.ipynb
  - API:
    - ref-client.md
    - ref-batch.md
    - ref-cli.md
    - ref-utils.md
  - Further reading: references.md
